name: Kali Stack Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "✅✅ Here for the growth"
      - name: Run script file
        id: script
        run: |
          chmod +x ${PWD}/.github/scripts/checkBranch.sh
          OUTPUT=$(./.github/scripts/checkBranch.sh)
          echo "::set-output name=CDK_BUCKET_NAME::$OUTPUT"
        shell: bash
      - name: Echo name
        run: echo ${{ steps.script.outputs.CDK_BUCKET_NAME }}
