name: Kali Stack Deploy

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅✅ Here for the growth"
      - run: chmod +x .github/scripts/checkBranch.sh && bash .github/scripts/checkBranch.sh