name: Kali Stack Deploy

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "✅✅ Here for the growth"
      - name: Run script file
        run: |
          chmod +x ${PWD}/.github/scripts/checkBranch.sh
          ${PWD}/.github/scripts/checkBranch.sh
        shell: bash
      - name: Echo name
        run: echo $CDK_BUCKET_NAME